FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install gunicorn && pip install --no-cache-dir -r requirements.txt

# Environment variables
ENV PORT=8391

# Expose the port the app runs on
EXPOSE $PORT