FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install gunicorn && pip install --no-cache-dir -r requirements.txt

# Create a new user
RUN adduser --disabled-password --gecos "" appuser

# Change to the new user
USER appuser

# Environment variables
ENV PORT=8391

# Expose the port the app runs on
EXPOSE $PORT

# Run the application
CMD ["gunicorn", "-b", "0.0.0.0:8391", "app.main:app", "--worker-class", "uvicorn.workers.UvicornWorker"]